export const clues = [
  `Your first treat is beneath the broken seat`,
  `Chocolate awaits amongst the chips`,
  `Come seek us where our voices sound,
  We cannot sing above the ground`,
  `Clue 4`,
  `Clue 5`,
  `Clue 6`,
  `Clue 7`,
  `Clue 8`,
  `Clue 9`,
  `Clue 10`,
  `Clue 11`,
  `Clue 12`,
  `Clue 13`,
  `Clue 14`,
  `Clue 15`,
  `Clue 16`,
  `Clue 17`,
  `Clue 18`,
  `Clue 19`,
  `Clue 20`,
  `Clue 21`,
  `Clue 22`,
  `Clue 23`,
  `Clue 24`
]